# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> || 5
  timeout: 5000
  port: 5432

development:
 adapter: sqlite3
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> || 5
 timeout: 5000
 database: db/development.sqlite3

test:
 adapter: sqlite3
 database: db/test.sqlite3

 production:
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> || 5
   timeout: 5000
   database: db/production.sqlite3
